from enum import Enum
class COMMAND:
    CMD_MOVE_STOP = "CMD_MOVE_STOP"
    CMD_MOVE_FORWARD = "CMD_MOVE_FORWARD"
    CMD_MOVE_BACKWARD = "CMD_MOVE_BACKWARD"
    CMD_MOVE_LEFT = "CMD_MOVE_LEFT"
    CMD_MOVE_RIGHT = "CMD_MOVE_RIGHT"
    CMD_TURN_LEFT = "CMD_TURN_LEFT"
    CMD_TURN_RIGHT = "CMD_TURN_RIGHT"
    CMD_LED_MOD = "CMD_LED_MOD"
    CMD_LED = "CMD_LED"
    CMD_BALANCE = "CMD_BALANCE"
    CMD_SONIC = "CMD_SONIC"
    CMD_HEAD = "CMD_HEAD"
    CMD_CALIBRATION = "CMD_CALIBRATION"
    CMD_POWER = "CMD_POWER"
    CMD_RELAX = "CMD_RELAX"
    CMD_CALIBRATION_MOD = "CMD_CALIBRATION_MOD"
    CMD_CALIBRATION_ALL = "CMD_CALIBRATION_ALL"
    CMD_TAKE_PHOTO = "CMD_TAKE_PHOTO"
    CMD_ADD_USER = "CMD_ADD_USER"
    CMD_HANDS_UP = "CMD_HANDS_UP"
    CMD_MUSIC_PLAY = "CMD_MUSIC_PLAY"
    CMD_MUSIC_STOP = "CMD_MUSIC_STOP"
    CMD_FUNC_1 = "CMD_CLENCH_LEFT"
    CMD_FUNC_2 = "CMD_CLENCH_LEFT"
    CMD_FUNC_3 = "CMD_LOOK_UP"
    CMD_FUNC_4 = "CMD_LOOK_DOWN"
    CMD_LOOK_STOP = "CMD_LOOK_STOP"
    CMD_FUNC_ABOUT = "CMD_FUNC_ABOUT"
    CMD_RADIO_PLAY = "CMD_RADIO_PLAY"
    CMD_RADIO_STOP = "CMD_RADIO_STOP"
    CMD_VIDEO = "CMD_VIDEO_TRANSMISSION"
    CMD_MENU = "CMD_MENU"

class LegNames(Enum):
    L = 0
    R = 1
    H = 2
    M = 3

class ServNames(Enum):
    A = 0
    B = 1
    C = 2
    D = 3
    E = 4

    # def __init__(self):
    #     pass