# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName("Calibration")
        Calibration.resize(713, 499)
        self.centralwidget = QtWidgets.QWidget(Calibration)
        self.centralwidget.setObjectName("centralwidget")
        self.button_end_calibration = QtWidgets.QPushButton(self.centralwidget)
        self.button_end_calibration.setGeometry(QtCore.QRect(80, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_end_calibration.setFont(font)
        self.button_end_calibration.setObjectName("button_end_calibration")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 90, 141, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_left = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_left.setFont(font)
        self.radioButton_left.setChecked(True)
        self.radioButton_left.setObjectName("radioButton_left")
        self.verticalLayout_2.addWidget(self.radioButton_left)
        self.radioButton_right = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_right.setFont(font)
        self.radioButton_right.setObjectName("radioButton_right")
        self.verticalLayout_2.addWidget(self.radioButton_right)
        self.radioButton_handLeft = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_handLeft.setFont(font)
        self.radioButton_handLeft.setObjectName("radioButton_handLeft")
        self.verticalLayout_2.addWidget(self.radioButton_handLeft)
        self.radioButton_handRight = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_handRight.setFont(font)
        self.radioButton_handRight.setObjectName("radioButton_handRight")
        self.verticalLayout_2.addWidget(self.radioButton_handRight)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 115, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 50, 311, 276))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setLineWidth(1)
        self.label_6.setWordWrap(False)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.button_A_less = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_A_less.setObjectName("button_A_less")
        self.horizontalLayout_6.addWidget(self.button_A_less)
        self.lineEdit_A = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_A.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_A.setFont(font)
        self.lineEdit_A.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.horizontalLayout_6.addWidget(self.lineEdit_A)
        self.button_A_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_A_more.setObjectName("button_A_more")
        self.horizontalLayout_6.addWidget(self.button_A_more)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.button_B_less = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_B_less.setObjectName("button_B_less")
        self.horizontalLayout_4.addWidget(self.button_B_less)
        self.lineEdit_B = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_B.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.horizontalLayout_4.addWidget(self.lineEdit_B)
        self.button_B_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_B_more.setObjectName("button_B_more")
        self.horizontalLayout_4.addWidget(self.button_B_more)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.button_C_less = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_C_less.setObjectName("button_C_less")
        self.horizontalLayout_7.addWidget(self.button_C_less)
        self.lineEdit_C = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_C.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_C.setFont(font)
        self.lineEdit_C.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.horizontalLayout_7.addWidget(self.lineEdit_C)
        self.button_C_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_C_more.setObjectName("button_C_more")
        self.horizontalLayout_7.addWidget(self.button_C_more)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.button_D_less = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_D_less.setObjectName("button_D_less")
        self.horizontalLayout_5.addWidget(self.button_D_less)
        self.lineEdit_D = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_D.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_D.setFont(font)
        self.lineEdit_D.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.horizontalLayout_5.addWidget(self.lineEdit_D)
        self.button_D_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_D_more.setObjectName("button_D_more")
        self.horizontalLayout_5.addWidget(self.button_D_more)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.button_E_less = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_E_less.setObjectName("button_E_less")
        self.horizontalLayout_8.addWidget(self.button_E_less)
        self.lineEdit_E = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_E.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_E.setFont(font)
        self.lineEdit_E.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_E.setObjectName("lineEdit_E")
        self.horizontalLayout_8.addWidget(self.lineEdit_E)
        self.button_E_more = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_E_more.setObjectName("button_E_more")
        self.horizontalLayout_8.addWidget(self.button_E_more)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 350, 481, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customCmd = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.customCmd.setFont(font)
        self.customCmd.setText("")
        self.customCmd.setObjectName("customCmd")
        self.horizontalLayout.addWidget(self.customCmd)
        self.button_custom_cmd = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_custom_cmd.setFont(font)
        self.button_custom_cmd.setObjectName("button_custom_cmd")
        self.horizontalLayout.addWidget(self.button_custom_cmd)
        Calibration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calibration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        Calibration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calibration)
        self.statusbar.setObjectName("statusbar")
        Calibration.setStatusBar(self.statusbar)

        self.retranslateUi(Calibration)
        QtCore.QMetaObject.connectSlotsByName(Calibration)
        CSS = """
                                        QMainWindow{
                                            background: white;
                                        }
                                        QSlider::groove:horizontal {
                                            border: 1px solid #565a5e;
                                            height: 10px;
                                            background: #eee;
                                            display: table-cell; 
                                            vertical-align: middle;
                                            border-radius: 4px;
                                        }
                                        QSlider::handle:horizontal {
                                            background: red;
                                            border: 1px solid #565a5e;
                                            width: 24px;
                                            height: 8px;
                                            border-radius: 8px;
                                        }
                                        QSlider::groove:vertical {
                                            border: 1px solid #565a5e;
                                            height: 71px;
                                            background: #eee;
                                            display: table-cell; 
                                            vertical-align: middle;
                                            border-radius: 4px;
                                        }
                                        QSlider::handle:vertical {
                                            background: red;
                                            border: 1px solid #565a5e;
                                            width: 22px;
                                            height: 8px;
                                            border-radius: 8px;
                                        }
                                        QPushButton{
                                            font-family: Ubuntu-Regular;
                                            background: #d4f0ff;
                                            border: 1px solid black;
                                            border-radius: 4px;
                                        }
                                        """
        self.setStyleSheet(CSS)

    def retranslateUi(self, Calibration):
        _translate = QtCore.QCoreApplication.translate
        Calibration.setWindowTitle(_translate("Calibration", "Калибровка"))
        self.button_end_calibration.setText(_translate("Calibration", "Сохранить"))
        self.radioButton_left.setText(_translate("Calibration", "Левая нога"))
        self.radioButton_right.setText(_translate("Calibration", "Правая нога"))
        self.radioButton_handLeft.setText(_translate("Calibration", "Левая рука"))
        self.radioButton_handRight.setText(_translate("Calibration", "Правая рука"))
        self.label.setText(_translate("Calibration", "Калибровка"))
        self.label_6.setText(_translate("Calibration", "A"))
        self.button_A_less.setText(_translate("Calibration", "<"))
        self.lineEdit_A.setText(_translate("Calibration", "-10"))
        self.button_A_more.setText(_translate("Calibration", ">"))
        self.label_7.setText(_translate("Calibration", "B"))
        self.button_B_less.setText(_translate("Calibration", "<"))
        self.lineEdit_B.setText(_translate("Calibration", "10"))
        self.button_B_more.setText(_translate("Calibration", ">"))
        self.label_8.setText(_translate("Calibration", "C"))
        self.button_C_less.setText(_translate("Calibration", "<"))
        self.lineEdit_C.setText(_translate("Calibration", "10"))
        self.button_C_more.setText(_translate("Calibration", ">"))
        self.label_9.setText(_translate("Calibration", "D"))
        self.button_D_less.setText(_translate("Calibration", "<"))
        self.lineEdit_D.setText(_translate("Calibration", "10"))
        self.button_D_more.setText(_translate("Calibration", ">"))
        self.label_10.setText(_translate("Calibration", "E"))
        self.button_E_less.setText(_translate("Calibration", "<"))
        self.lineEdit_E.setText(_translate("Calibration", "10"))
        self.button_E_more.setText(_translate("Calibration", ">"))
        self.button_custom_cmd.setText(_translate("Calibration", "Отправить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calibration = QtWidgets.QMainWindow()
    ui = Ui_Calibration()
    ui.setupUi(Calibration)
    Calibration.show()
    sys.exit(app.exec_())
