# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.Button_Forward = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Forward.setGeometry(QtCore.QRect(170, 360, 101, 51))
        self.Button_Forward.setObjectName("Button_Forward")
        self.Button_Backward = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Backward.setGeometry(QtCore.QRect(170, 420, 101, 41))
        self.Button_Backward.setObjectName("Button_Backward")
        self.Button_Right = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Right.setGeometry(QtCore.QRect(280, 420, 91, 41))
        self.Button_Right.setObjectName("Button_Right")
        self.Button_Left = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Left.setGeometry(QtCore.QRect(70, 420, 91, 41))
        self.Button_Left.setObjectName("Button_Left")
        self.slider_speed = QtWidgets.QSlider(self.centralwidget)
        self.slider_speed.setGeometry(QtCore.QRect(380, 370, 22, 141))
        self.slider_speed.setMinimum(2)
        self.slider_speed.setMaximum(10)
        self.slider_speed.setProperty("value", 8)
        self.slider_speed.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed.setObjectName("slider_speed")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 350, 47, 13))
        self.label_2.setObjectName("label_2")
        self.Button_Sonic = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Sonic.setGeometry(QtCore.QRect(430, 240, 101, 41))
        self.Button_Sonic.setObjectName("Button_Sonic")
        self.pushButton_calibration = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calibration.setGeometry(QtCore.QRect(430, 190, 101, 41))
        self.pushButton_calibration.setObjectName("pushButton_calibration")
        self.Video_label = QtWidgets.QLabel(self.centralwidget)
        self.Video_label.setGeometry(QtCore.QRect(20, 50, 400, 300))
        self.Video_label.setObjectName("Video_label")
        self.Take_photo_button = QtWidgets.QPushButton(self.centralwidget)
        self.Take_photo_button.setGeometry(QtCore.QRect(430, 140, 101, 41))
        self.Take_photo_button.setObjectName("Take_photo_button")
        self.hands_up = QtWidgets.QPushButton(self.centralwidget)
        self.hands_up.setGeometry(QtCore.QRect(650, 440, 101, 41))
        self.hands_up.setObjectName("hands_up")
        self.Play_Music = QtWidgets.QPushButton(self.centralwidget)
        self.Play_Music.setGeometry(QtCore.QRect(430, 290, 101, 41))
        self.Play_Music.setObjectName("Play_Music")
        self.Pause_Music = QtWidgets.QPushButton(self.centralwidget)
        self.Pause_Music.setGeometry(QtCore.QRect(430, 340, 101, 41))
        self.Pause_Music.setObjectName("Pause_Music")
        self.func3 = QtWidgets.QPushButton(self.centralwidget)
        self.func3.setGeometry(QtCore.QRect(540, 390, 101, 41))
        self.func3.setObjectName("func3")
        self.func2 = QtWidgets.QPushButton(self.centralwidget)
        self.func2.setGeometry(QtCore.QRect(540, 340, 101, 41))
        self.func2.setObjectName("func2")
        self.func1 = QtWidgets.QPushButton(self.centralwidget)
        self.func1.setGeometry(QtCore.QRect(540, 290, 101, 41))
        self.func1.setObjectName("func1")
        self.func4 = QtWidgets.QPushButton(self.centralwidget)
        self.func4.setGeometry(QtCore.QRect(540, 440, 101, 41))
        self.func4.setObjectName("func4")
        self.Radio_ON = QtWidgets.QPushButton(self.centralwidget)
        self.Radio_ON.setGeometry(QtCore.QRect(430, 390, 101, 41))
        self.Radio_ON.setObjectName("Radio_ON")
        self.about5 = QtWidgets.QPushButton(self.centralwidget)
        self.about5.setGeometry(QtCore.QRect(650, 390, 101, 41))
        self.about5.setObjectName("about5")
        self.about4 = QtWidgets.QPushButton(self.centralwidget)
        self.about4.setGeometry(QtCore.QRect(650, 340, 101, 41))
        self.about4.setObjectName("about4")
        self.Radio_OFF = QtWidgets.QPushButton(self.centralwidget)
        self.Radio_OFF.setGeometry(QtCore.QRect(430, 440, 101, 41))
        self.Radio_OFF.setObjectName("Radio_OFF")
        self.about2 = QtWidgets.QPushButton(self.centralwidget)
        self.about2.setGeometry(QtCore.QRect(650, 240, 101, 41))
        self.about2.setObjectName("about2")
        self.about1 = QtWidgets.QPushButton(self.centralwidget)
        self.about1.setGeometry(QtCore.QRect(650, 190, 101, 41))
        self.about1.setObjectName("about1")
        self.About0 = QtWidgets.QPushButton(self.centralwidget)
        self.About0.setGeometry(QtCore.QRect(650, 140, 101, 41))
        self.About0.setObjectName("About0")
        self.about3 = QtWidgets.QPushButton(self.centralwidget)
        self.about3.setGeometry(QtCore.QRect(650, 290, 101, 41))
        self.about3.setObjectName("about3")
        self.MENU = QtWidgets.QPushButton(self.centralwidget)
        self.MENU.setGeometry(QtCore.QRect(540, 140, 101, 41))
        self.MENU.setObjectName("MENU")
        self.Video_ON = QtWidgets.QPushButton(self.centralwidget)
        self.Video_ON.setGeometry(QtCore.QRect(540, 190, 101, 41))
        self.Video_ON.setObjectName("Video_ON")
        self.Video_OFF = QtWidgets.QPushButton(self.centralwidget)
        self.Video_OFF.setGeometry(QtCore.QRect(540, 240, 101, 41))
        self.Video_OFF.setObjectName("Video_OFF")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 10, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_err = QtWidgets.QLabel(self.centralwidget)
        self.label_err.setGeometry(QtCore.QRect(290, 50, 190, 25))
        self.label_err.setObjectName("label_err")
        self.lineEdit.setFont(font)
        self.label_err.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        CSS = """
                                        QMainWindow{
                                            background: white;
                                        }

                                        QSlider::groove:horizontal {
                                            border: 1px solid #565a5e;
                                            height: 10px;
                                            background: #eee;
                                            display: table-cell; 
                                            vertical-align: middle;
                                            border-radius: 4px;
                                        }
                                        QSlider::handle:horizontal {
                                            background: red;
                                            border: 1px solid #565a5e;
                                            width: 24px;
                                            height: 8px;
                                            border-radius: 8px;
                                        }
                                        QSlider::groove:vertical {
                                            border: 1px solid #565a5e;
                                            height: 71px;
                                            background: #eee;
                                            display: table-cell; 
                                            vertical-align: middle;
                                            border-radius: 4px;
                                        }
                                        QSlider::handle:vertical {
                                            background: red;
                                            border: 1px solid #565a5e;
                                            width: 22px;
                                            height: 8px;
                                            border-radius: 8px;
                                        }
                                        QPushButton{
                                            font-family: Ubuntu-Regular;
                                            background: #d4f0ff;
                                            border: 1px solid black;
                                            border-radius: 4px;
                                        }
                                        """
        self.setStyleSheet(CSS)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окно клиента"))
        self.label.setText(_translate("MainWindow", "Соединиться с сервером:"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.Button_Forward.setText(_translate("MainWindow", "Вперед"))
        self.Button_Backward.setText(_translate("MainWindow", "Назад"))
        self.Button_Right.setText(_translate("MainWindow", "Вправо"))
        self.Button_Left.setText(_translate("MainWindow", "Влево"))
        self.label_2.setText(_translate("MainWindow", "Скорость"))
        self.Button_Sonic.setText(_translate("MainWindow", "Sonic"))
        self.pushButton_calibration.setText(_translate("MainWindow", "Калибровка"))
        self.Video_label.setText(_translate("MainWindow", " "))
        self.Take_photo_button.setText(_translate("MainWindow", "Добавить\nпользователя"))
        self.hands_up.setText(_translate("MainWindow", "Помахать"))
        self.Play_Music.setText(_translate("MainWindow", "Вкл музыку"))
        self.Pause_Music.setText(_translate("MainWindow", "Выкл музыку"))
        self.func3.setText(_translate("MainWindow", "Посмотреть вверх"))
        self.func2.setText(_translate("MainWindow", "Правая рука"))
        self.func1.setText(_translate("MainWindow", "Левая рука"))
        self.func4.setText(_translate("MainWindow", "Посмотреть вниз"))
        self.Radio_ON.setText(_translate("MainWindow", "Radio вкл"))
        self.about5.setText(_translate("MainWindow", "О нейросетях"))
        self.about4.setText(_translate("MainWindow", "О питании"))
        self.Radio_OFF.setText(_translate("MainWindow", "Radio выкл"))
        self.about2.setText(_translate("MainWindow", "О коде"))
        self.about1.setText(_translate("MainWindow", "Вкл о себе"))
        self.About0.setText(_translate("MainWindow", "Выкл О себе"))
        self.about3.setText(_translate("MainWindow", "О платах"))
        self.MENU.setText(_translate("MainWindow", "В МЕНЮ"))
        self.Video_ON.setText(_translate("MainWindow", "Вкл видео"))
        self.Video_OFF.setText(_translate("MainWindow", "Выкл Видео"))
        self.lineEdit.setText(_translate("MainWindow", "192.168.1."))
        self.label_err.setText(_translate("MainWindow", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
