# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_user(object):
    def setupUi(self, Add_user):
        Add_user.setObjectName("Add_user")
        Add_user.resize(690, 400)
        self.centralwidget = QtWidgets.QWidget(Add_user)
        self.centralwidget.setObjectName("centralwidget")
        self.Video_Label = QtWidgets.QLabel(self.centralwidget)
        self.Video_Label.setGeometry(QtCore.QRect(30, 30, 400, 300))
        self.Video_Label.setObjectName("Video_Label")
        self.takePhotoButton = QtWidgets.QPushButton(self.centralwidget)
        self.takePhotoButton.setGeometry(QtCore.QRect(460, 130, 75, 23))
        self.takePhotoButton.setObjectName("takePhotoButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(460, 100, 211, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 80, 81, 16))
        self.label_2.setObjectName("label_2")
        Add_user.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Add_user)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Add_user.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Add_user)
        self.statusbar.setObjectName("statusbar")
        Add_user.setStatusBar(self.statusbar)

        self.retranslateUi(Add_user)
        QtCore.QMetaObject.connectSlotsByName(Add_user)
        CSS = """
                                QMainWindow{
                                    background: white;
                                }
                                QSlider::groove:horizontal {
                                    border: 1px solid #565a5e;
                                    height: 10px;
                                    background: #eee;
                                    display: table-cell; 
                                    vertical-align: middle;
                                    border-radius: 4px;
                                }
                                QSlider::handle:horizontal {
                                    background: red;
                                    border: 1px solid #565a5e;
                                    width: 24px;
                                    height: 8px;
                                    border-radius: 8px;
                                }
                                QSlider::groove:vertical {
                                    border: 1px solid #565a5e;
                                    height: 71px;
                                    background: #eee;
                                    display: table-cell; 
                                    vertical-align: middle;
                                    border-radius: 4px;
                                }
                                QSlider::handle:vertical {
                                    background: red;
                                    border: 1px solid #565a5e;
                                    width: 22px;
                                    height: 8px;
                                    border-radius: 8px;
                                }
                                QPushButton{
                                    font-family: Ubuntu-Regular;
                                    background: #d4f0ff;
                                    border: 1px solid black;
                                    border-radius: 4px;
                                }
                                """
        self.setStyleSheet(CSS)

    def retranslateUi(self, Add_user):
        _translate = QtCore.QCoreApplication.translate
        Add_user.setWindowTitle(_translate("Add_user", "Добавление пользователя"))
        self.Video_Label.setText(_translate("Add_user", " "))
        self.takePhotoButton.setText(_translate("Add_user", "Take Photo"))
        self.label_2.setText(_translate("Add_user", "Введите имя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_user = QtWidgets.QMainWindow()
    ui = Ui_Add_user()
    ui.setupUi(Add_user)
    Add_user.show()
    sys.exit(app.exec_())
